[2024-07-22T00:22:14.700+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T00:22:14.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task manual__2024-07-22T00:22:12.869958+00:00 [queued]>
[2024-07-22T00:22:14.738+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task manual__2024-07-22T00:22:12.869958+00:00 [queued]>
[2024-07-22T00:22:14.740+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-22T00:22:14.761+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2024-07-22 00:22:12.869958+00:00
[2024-07-22T00:22:14.769+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=930) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T00:22:14.771+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'first_task', 'manual__2024-07-22T00:22:12.869958+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpiuz_z2gp']
[2024-07-22T00:22:14.773+0000] {standard_task_runner.py:63} INFO - Started process 931 to run task
[2024-07-22T00:22:14.773+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask first_task
[2024-07-22T00:22:14.840+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v5.first_task manual__2024-07-22T00:22:12.869958+00:00 [running]> on host eefce25a52e3
[2024-07-22T00:22:15.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T00:22:12.869958+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T00:22:12.869958+00:00'
[2024-07-22T00:22:15.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T00:22:15.192+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-22T00:22:15.195+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello World, this is the first task to be done']
[2024-07-22T00:22:15.211+0000] {subprocess.py:86} INFO - Output:
[2024-07-22T00:22:15.215+0000] {subprocess.py:93} INFO - Hello World, this is the first task to be done
[2024-07-22T00:22:15.216+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-22T00:22:15.221+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T00:22:15.272+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=first_task, run_id=manual__2024-07-22T00:22:12.869958+00:00, execution_date=20240722T002212, start_date=20240722T002214, end_date=20240722T002215
[2024-07-22T00:22:15.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-22T00:22:15.343+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-07-22T00:22:15.348+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
